CREATE TABLE RATING (TCONST VARCHAR(255) NOT NULL, AVERAGERATING FLOAT, NUMVOTES INTEGER, PRIMARY KEY (TCONST));
CREATE TABLE TITLE (TCONST VARCHAR(255) NOT NULL, PRIMARYTITLE VARCHAR(255), STARTYEAR INTEGER, PRIMARY KEY (TCONST));
ALTER TABLE RATING ADD CONSTRAINT FK_RATING_TCONST FOREIGN KEY (TCONST) REFERENCES TITLE (TCONST);
